# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

# change this name to the name of a file you're using at the root directory
< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
# change the id below to a working one after you upload a file
POST http://localhost:3333/videos/7641258c-6bff-4322-89a6-ff2ce7ec3232/transcription
Content-Type: application/json

{
  "prompt": "keywords, comprehend, explain"
}

###

# @name create-transcription
POST http://localhost:3333/ai/complete
Content-Type: application/json

# change the id below to a working one after you uploaded and transcripted a file
{
  "videoId": "7641258c-6bff-4322-89a6-ff2ce7ec3232",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}
